spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTH_DB}

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    hu.szarvas: DEBUG
